import { data } from "./data.js";

// Get elements
const container = document.querySelector('.container')
const validateBtn = document.querySelector('.validate')

// Variables
let questionNumber = 0
const correctAnswersArray = []
const userAnswersArray = []
let numberOfChoicesLength = data[questionNumber].answers.length


// Create template
const createTemplate = () => {
    // --- creation of the card container
    const cardContainer = document.createElement('div')
    cardContainer.classList.add('cardContainer')
    // --- insertion of the card container
    container.appendChild(cardContainer)
    // --- creation of the question 
    const questionText = document.createElement('h4')
    questionText.classList.add('questionText')
    // --- insertion of the question
    cardContainer.appendChild(questionText)
    // --- creation of the answers container
    const answersContainer = document.createElement('div')
    answersContainer.classList.add('answersContainer')
    // --- insertion of the answers container
    cardContainer.appendChild(answersContainer)
    for (let i = 0; i < numberOfChoicesLength; i++){
        // --- creation of a single answer container
        const answerContainer = document.createElement('div')
        answerContainer.classList.add('answerContainer')
        // --- insertion of a single answer container
        answersContainer.appendChild(answerContainer)
        // --- creation of the radio input
        const answerChoiceInput = document.createElement('input')
        answerChoiceInput.setAttribute('type','radio')
        if ( i === 0){
            answerChoiceInput.setAttribute('checked', true)
        }
        answerChoiceInput.setAttribute('name',`question${questionNumber}`)
        answerChoiceInput.setAttribute('id', `id${i}`)
        // --- insertion of the radio input
        answerContainer.appendChild(answerChoiceInput)
        // --- creation of the label
        const answerLabel = document.createElement('label')
        answerLabel.setAttribute('for',`id${i}`)
        answerLabel.setAttribute('id', `label${i}`)
        // --- insertion of the label
        answerContainer.appendChild(answerLabel)
    }
}

// Call the template when the page loads
createTemplate()

// Get elements generated by the template
const questionText = document.querySelector('.questionText')
const answerChoiceOne = document.getElementById('id0')
const labelOne = document.getElementById('label0')
const answerChoiceTwo = document.getElementById('id1')
const labelTwo =document.getElementById('label1')
const answerChoiceThree = document.getElementById('id2')
const labelThree = document.getElementById('label2')


// Fill the template with the first question
const fillTemplate = () => {

    questionText.innerText = data[questionNumber].question
    const questionAnswers = data[questionNumber].answers
    for (let i = 0 ; i < numberOfChoicesLength; i++){
        const currentInput = document.getElementById(`id${i}`)
        const currentLabel = document.getElementById(`label${i}`)
        currentInput.setAttribute('value',questionAnswers[i].text)
        currentInput.innerText = questionAnswers[i].text

    }
    // answerLabel.innerText = questionAnswers[i].text
    // answerChoiceInput.setAttribute('value',questionAnswers[i].text)
    // answerLabel.innerText = questionAnswers[i].text
}


// Call the filling function when page loads for the first question
fillTemplate()
// Functions 
const createCorrectAnswersArray = () => {
    for (let element of data){
        for(let i = 0; i < element.answers.length; i++){
            if (element.answers[i].correct === true){
                correctAnswersArray.push(element.answers[i].text)
            }
        }
    }
}

console.log(correctAnswersArray)

// --- functions called by the event listener
/**
 * Register user answer
 */
const registerUserAnswer = () => {
    // register the user response in an array
    const choices = document.querySelectorAll("input[type='radio']")
    // console.log(choices)
    for (let choice of choices){
        // console.log(choice)
        if (choice.checked === true){
            userAnswersArray.push(choice.value)
        }
    }
    console.log(userAnswersArray)
}
const generateNewQuestion = () => {

}

const nextQuestion = () => {
    console.log('next')
    if (userAnswersArray.length === questionNumber){
        registerUserAnswer()
    }
    generateNewQuestion()
    questionNumber++
}

const endQuizz = () => {
    console.log('end')
}

const resetQuizz = () => {
    console.log('reset')
}

const handleAnswer = (e) => {
    // three values possible for validateBtn.innertext
    // --- suivant 
    // ---------- register the user response
    // ---------- generate and display the next question
    // --- valider / terminer questionnaire
    // ----------- display with all the questions, the user answers and the correct answers
    // --- rejouer
    // ----------- after the results page, offer the possibility to replay
    switch (e.target.innerText){
        case 'Suivant':
            nextQuestion()
            break
        case 'Valider':
            endQuizz()
            break
        case 'Rejouer':
            resetQuizz()
            break
        default :
            console.log('Erreur')
    }
}

// Function call
 createCorrectAnswersArray()

// Event listener
validateBtn.addEventListener('click', handleAnswer)